Tutritp01/TgBot

.gitignore, tg-bot/src/main/java/com/tutrit/tgbot/example/constants/ChatBotCommands.java
Created Enum for chatBot commands
https://schneidervs.atlassian.net/browse/TGBOT-6
And updated .gitignore
=> [Tgbot 6] - Create Enum for chatBot commands

tg-bot/pom.xml
add SQLite JDBC dependency to project
=> https://schneidervs.atlassian.net/browse/TGBOT-9

tg-bot/src/main/java/com/tutrit/tgbot/example/bean/User.java, tg-bot/src/main/java/com/tutrit/tgbot/example/constants/Role.java
https://schneidervs.atlassian.net/browse/TGBOT-5
=> create bean User and enum Role

tg-bot/src/main/java/com/tutrit/tgbot/example/bean/Car.java, tg-bot/src/main/java/com/tutrit/tgbot/example/repository/CarRepository.java, tg-bot/src/test/java/com/tutrit/tgbot/example/repository/CarRepositoryTest.java
Created Car repository & Bean using List, CRUD and Tests
https://schneidervs.atlassian.net/browse/TGBOT-26
=> [Tgbot 26] - Create Car repository & Bean using List, CRUD and Tests

stoservice/src/main/java/com/tutrit/stoservice/bean/Car.java, stoservice/src/main/java/com/tutrit/stoservice/repository/CarRepository.java, stoservice/src/test/java/com/tutrit/stoservice/repository/CarRepositoryTest.java
Completed the task of creating a Car bean, CarRepository using a list and tests for it.
=> [Tgbot26] - Create Car repository & Bean using List, CRUD and Tests

stoservice/src/main/java/com/tutrit/stoservice/bean/Engineer.java, stoservice/src/main/java/com/tutrit/stoservice/repository/EngineerRepository.java, stoservice/src/test/java/com/tutrit/stoservice/repository/EngineerRepositoryTest.java
https://schneidervs.atlassian.net/browse/TGBOT-25
=> [TGBOT-25] Create Engineer repository & Bean using Arrays, CRUD and Tests

stoservice/src/main/java/com/tutrit/stoservice/provider/CustomerProvider.java, stoservice/src/test/java/com/tutrit/stoservice/provider/CustomerProviderTest.java
https://schneidervs.atlassian.net/browse/TGBOT-44
Created a CustomerProvider class that exposes 5 customer objects.
There are also tests for the methods of the CustomerProvider class.
=> Tgbot 44 - Create object provider for Customer objects

stoservice/src/main/java/com/tutrit/stoservice/bean/Order.java, stoservice/src/main/java/com/tutrit/stoservice/provider/OrderProvider.java, stoservice/src/test/java/com/tutrit/stoservice/provider/OrderProviderTest.java
https://schneidervs.atlassian.net/browse/TGBOT-45
=> TGBOT-45-create-object-provider-for-order-objects

stoservice/src/main/java/com/tutrit/stoservice/bean/Engineer.java, stoservice/src/main/java/com/tutrit/stoservice/provider/EngineerProvider.java, stoservice/src/main/java/com/tutrit/stoservice/repository/EngineerRepository.java, stoservice/src/test/java/com/tutrit/stoservice/provider/EngineerProviderTest.java
Create class that will provide 3 engineer objects.
https://schneidervs.atlassian.net/browse/TGBOT-43
=> Tgbot 43 create object provider for engineer objects

stoservice/src/main/java/com/tutrit/stoservice/bean/User.java, stoservice/src/main/java/com/tutrit/stoservice/repository/UserRepository.java, stoservice/src/test/java/com/tutrit/stoservice/repository/UserRepositoryTest.java
=> TGBOT-14-Create_User_repository_&_Bean_using_Map,_CRUD_and_Tests

stoservice/src/main/java/com/tutrit/stoservice/provider/UserProvider.java
=> TGBOT-66 Create object provider for User objects

stoservice/src/main/java/com/tutrit/stoservice/StoserviceApplication.java, stoservice/src/main/java/com/tutrit/stoservice/provider/EngineerProvider.java, stoservice/src/main/java/com/tutrit/stoservice/provider/OrderProvider.java, stoservice/src/main/java/com/tutrit/stoservice/provider/UserProvider.java
=> WIP TGBOT-46 Load data on application start

stoservice/src/main/java/com/tutrit/stoservice/StoserviceApplication.java, stoservice/src/main/java/com/tutrit/stoservice/provider/OrderProvider.java, stoservice/src/main/java/com/tutrit/stoservice/repository/EngineerRepository.java, stoservice/src/main/java/com/tutrit/stoservice/repository/OrderRepository.java, stoservice/src/test/java/com/tutrit/stoservice/StoserviceApplicationTest.java, stoservice/src/test/java/com/tutrit/stoservice/StoserviceApplicationTests.java, stoservice/src/test/java/com/tutrit/stoservice/provider/CarProviderTest.java, stoservice/src/test/java/com/tutrit/stoservice/repository/CarRepositoryTest.java, stoservice/src/test/java/com/tutrit/stoservice/repository/CustomerRepositoryTest.java, stoservice/src/test/java/com/tutrit/stoservice/repository/EngineerRepositoryTest.java, stoservice/src/test/java/com/tutrit/stoservice/repository/OrderRepositoryTest.java
https://schneidervs.atlassian.net/browse/TGBOT-48
Description
After application loads, it should be in state for waiting user commands.
first command to process is to print all data that has been loaded in application
=> TGBOT-48-process-command-show-data

stoservice/src/main/java/com/tutrit/stoservice/StoserviceApplication.java, stoservice/src/main/java/com/tutrit/stoservice/provider/DemoDataLoader.java
https://schneidervs.atlassian.net/jira/software/projects/TGBOT/boards/2?selectedIssue=TGBOT-69
Moved data generation to a separate class
=> Tgbot-69 Move data creation to separate class

stoservice/src/main/java/com/tutrit/stoservice/controller/DataController.java
https://schneidervs.atlassian.net/jira/software/projects/TGBOT/boards/2?selectedIssue=TGBOT-105
Added DataController for show data
=> TGBOT-105 Process show data command

stoservice/src/main/java/com/tutrit/stoservice/controller/ExitController.java
https://schneidervs.atlassian.net/browse/TGBOT-73
=> TGBOT-73 Process exit command

stoservice/src/main/java/com/tutrit/stoservice/controller/NotACommandController.java
https://schneidervs.atlassian.net/browse/TGBOT-74
=> TGBOT-74 Process if  command not found

stoservice/src/main/java/com/tutrit/stoservice/controller/Command.java, stoservice/src/main/java/com/tutrit/stoservice/controller/Request.java, stoservice/src/main/java/com/tutrit/stoservice/controller/RequestDispatcher.java, stoservice/src/main/java/com/tutrit/stoservice/controller/Response.java
https://schneidervs.atlassian.net/browse/TGBOT-71
=> TGBOT-71 Сreate request dispatcher

stoservice/src/main/java/com/tutrit/stoservice/repository/EngineerRepository.java
https://schneidervs.atlassian.net/browse/TGBOT-67
=> TGBOT-67Change the modifier to static for engineer repository 

stoservice/src/main/java/com/tutrit/stoservice/repository/EngineerRepository.java, stoservice/src/main/java/com/tutrit/stoservice/service/MenuService.java
add method findAll(); in EngineerRepository, add import in MenuServise.
=> Git checkout  b tgbot 70 create menu

stoservice/src/main/java/com/tutrit/stoservice/repository/Repository.java
https://schneidervs.atlassian.net/jira/software/projects/TGBOT/boards/2?selectedIssue=TGBOT-93
Interface Repository has been created
=> TGBOT-93 create interface Repository

stoservice/src/main/java/com/tutrit/stoservice/repository/CarRepository.java, stoservice/src/test/java/com/tutrit/stoservice/repository/CarRepositoryTest.java
https://schneidervs.atlassian.net/jira/software/projects/TGBOT/boards/2?selectedIssue=TGBOT-94
CarRepository is implemented according to the Repository interface.
Tests have been updated.
=> Tgbot-94 Implement crud repository to car repository

stoservice/src/main/java/com/tutrit/stoservice/provider/DemoDataLoader.java, stoservice/src/main/java/com/tutrit/stoservice/repository/UserRepository.java, stoservice/src/test/java/com/tutrit/stoservice/repository/UserRepositoryTest.java
https://schneidervs.atlassian.net/jira/software/projects/TGBOT/boards/2?selectedIssue=TGBOT-98
UserRepository is implemented according to the Repository interface.
Tests have been updated.
=> Tgbot 98 Implement crud repository to user repository

stoservice/src/main/java/com/tutrit/stoservice/repository/CustomerRepository.java, stoservice/src/test/java/com/tutrit/stoservice/repository/CustomerRepositoryTest.java
https://schneidervs.atlassian.net/browse/TGBOT-95
=>  TGBOT-95 Iimplement crud repository to customer repository

stoservice/src/main/java/com/tutrit/stoservice/controller/Command.java, stoservice/src/main/java/com/tutrit/stoservice/controller/HelpController.java, stoservice/src/main/java/com/tutrit/stoservice/controller/RequestDispatcher.java
https://schneidervs.atlassian.net/browse/TGBOT-75
=> TGBOT-75 Process help

stoservice/src/main/java/com/tutrit/stoservice/repository/OrderRepository.java, stoservice/src/test/java/com/tutrit/stoservice/repository/OrderRepositoryTest.java
https://schneidervs.atlassian.net/jira/software/projects/TGBOT/boards/2?selectedIssue=TGBOT-97
=> Git checkout  b tgbot 97 implement crud repository to order repository

stoservice/src/main/java/com/tutrit/stoservice/provider/DemoDataLoader.java, stoservice/src/main/java/com/tutrit/stoservice/repository/EngineerRepository.java, stoservice/src/test/java/com/tutrit/stoservice/repository/EngineerRepositoryTest.java
Implement CRUD repository to EngineerRepository
https://schneidervs.atlassian.net/browse/TGBOT-96
=> TGBOT-96-implement-crud-repository-to-engineer-repository

stoservice/src/main/java/com/tutrit/stoservice/controller/DataController.java
https://schneidervs.atlassian.net/jira/software/projects/TGBOT/boards/2?selectedIssue=TGBOT-72
DataController has been changed
=> TGBOT-72 create DataController

stoservice/src/main/java/com/tutrit/stoservice/StoserviceApplication.java, stoservice/src/main/java/com/tutrit/stoservice/context/ApplicationContext.java, stoservice/src/main/java/com/tutrit/stoservice/context/ApplicationContextLoader.java
https://schneidervs.atlassian.net/jira/software/projects/TGBOT/boards/2?selectedIssue=TGBOT-104
ApplicationContext and ApplicationContextLoader have been created
=> Tgbot 104 create application context class

stoservice/src/main/java/com/tutrit/stoservice/controller/CommandController.java, stoservice/src/main/java/com/tutrit/stoservice/controller/DataController.java, stoservice/src/main/java/com/tutrit/stoservice/controller/ExitController.java, stoservice/src/main/java/com/tutrit/stoservice/controller/HelpController.java, stoservice/src/main/java/com/tutrit/stoservice/controller/NotACommandController.java, stoservice/src/main/java/com/tutrit/stoservice/provider/DemoDataLoader.java, stoservice/src/main/java/com/tutrit/stoservice/provider/OrderProvider.java, stoservice/src/main/java/com/tutrit/stoservice/provider/UserProvider.java, stoservice/src/test/java/com/tutrit/stoservice/provider/OrderProviderTest.java
https://schneidervs.atlassian.net/jira/software/projects/TGBOT/boards/2?selectedIssue=TGBOT-146
CommandController interface has been created and implemented.
Also changed DemoDataLoader, UserProvider and OrderProvider.
=> Tgbot-146 create interface command controller

stoservice/src/main/java/com/tutrit/stoservice/bean/Promo.java, stoservice/src/main/java/com/tutrit/stoservice/bean/PromoStatus.java, stoservice/src/main/java/com/tutrit/stoservice/repository/PromoRepository.java, stoservice/src/test/java/com/tutrit/stoservice/repository/PromoRepositoryTest.java
https://schneidervs.atlassian.net/browse/TGBOT-120
Promo class created with repository, promo statuses and tests
=> Tgbot-120 create class promo

stoservice/src/main/java/com/tutrit/stoservice/bean/User.java, stoservice/src/main/java/com/tutrit/stoservice/context/ApplicationContextLoader.java, stoservice/src/main/java/com/tutrit/stoservice/controller/Command.java, stoservice/src/main/java/com/tutrit/stoservice/controller/RequestDispatcher.java, stoservice/src/main/java/com/tutrit/stoservice/controller/UserController.java, stoservice/src/main/java/com/tutrit/stoservice/repository/UserRepository.java, stoservice/src/main/java/com/tutrit/stoservice/service/UserService.java, stoservice/src/main/java/com/tutrit/stoservice/util/ParseUser.java, stoservice/src/test/java/com/tutrit/stoservice/controller/IntUserControllerTest.java, stoservice/src/test/java/com/tutrit/stoservice/controller/RequestDispatcherTest.java, stoservice/src/test/java/com/tutrit/stoservice/controller/UserControllerTest.java, stoservice/src/test/java/com/tutrit/stoservice/mock/UserRepositoryMock.java, stoservice/src/test/java/com/tutrit/stoservice/provider/UserProviderTest.java, stoservice/src/test/java/com/tutrit/stoservice/repository/UserRepositoryTest.java, stoservice/src/test/java/com/tutrit/stoservice/service/UserServiceTest.java, stoservice/src/test/java/com/tutrit/stoservice/spy/UserControllerSpy.java
https://schneidervs.atlassian.net/jira/software/projects/TGBOT/boards/2?selectedIssue=TGBOT-103
UserService created without tests
=> TGBOT-103 create UserService

stoservice/src/main/java/com/tutrit/stoservice/context/ApplicationContextLoader.java, stoservice/src/main/java/com/tutrit/stoservice/controller/Command.java, stoservice/src/main/java/com/tutrit/stoservice/controller/CustomerController.java, stoservice/src/main/java/com/tutrit/stoservice/controller/RequestDispatcher.java, stoservice/src/main/java/com/tutrit/stoservice/service/CustomerService.java, stoservice/src/main/java/com/tutrit/stoservice/service/MenuService.java, stoservice/src/main/java/com/tutrit/stoservice/utils/GetCustomer.java, stoservice/src/test/java/com/tutrit/stoservice/controller/CustomerControllerTest.java, stoservice/src/test/java/com/tutrit/stoservice/mock/CustomerControllerSpy.java, stoservice/src/test/java/com/tutrit/stoservice/mock/CustomerRepositoryMock.java, stoservice/src/test/java/com/tutrit/stoservice/mock/CustomerServiceMock.java
https://schneidervs.atlassian.net/browse/TGBOT-100
=> [TGBOT-100] Create customer service

stoservice/src/main/java/com/tutrit/stoservice/context/ApplicationContextLoader.java, stoservice/src/main/java/com/tutrit/stoservice/controller/Command.java, stoservice/src/main/java/com/tutrit/stoservice/controller/EngineerController.java, stoservice/src/main/java/com/tutrit/stoservice/controller/RequestDispatcher.java, stoservice/src/main/java/com/tutrit/stoservice/service/EngineerService.java, stoservice/src/main/java/com/tutrit/stoservice/utils/UserInputToEngineer.java, stoservice/src/test/java/com/tutrit/stoservice/controller/EngineerControllerTest.java, stoservice/src/test/java/com/tutrit/stoservice/service/EngineerServiceTest.java, stoservice/src/test/java/com/tutrit/stoservice/service/mock/EngineerRepositoryMock.java, stoservice/src/test/java/com/tutrit/stoservice/utils/UserInputToEngineerTest.java
https://schneidervs.atlassian.net/browse/TGBOT-101
=> TGBOT-101-create-engineer-service-v3

stoservice/src/main/java/com/tutrit/stoservice/bean/Message.java, stoservice/src/main/java/com/tutrit/stoservice/bean/MessageStatus.java, stoservice/src/main/java/com/tutrit/stoservice/repository/MessageRepository.java, stoservice/src/test/java/com/tutrit/stoservice/repository/MessageRepositoryTest.java
https://schneidervs.atlassian.net/jira/software/projects/TGBOT/boards/2?selectedIssue=TGBOT-117
=> [TGBOT-117] Create Message Repository

stoservice/src/main/java/com/tutrit/stoservice/controller/RequestDispatcher.java
https://schneidervs.atlassian.net/browse/TGBOT-166
=> Refactor "RequestDispather"

stoservice/src/main/java/com/tutrit/stoservice/context/ApplicationContextLoader.java, stoservice/src/main/java/com/tutrit/stoservice/controller/DataController.java
https://schneidervs.atlassian.net/jira/software/projects/TGBOT/boards/2?selectedIssue=TGBOT-165
=> [TGBOT-165]-refacton-data-controller

stoservice/src/main/java/com/tutrit/stoservice/controller/DataController.java
https://schneidervs.atlassian.net/jira/software/projects/TGBOT/boards/2?selectedIssue=TGBOT-164
=> [TGBOT-164] refactor-logger-by-request-dispatcher

stoservice/src/main/java/com/tutrit/stoservice/StoserviceApplication.java, stoservice/src/main/java/com/tutrit/stoservice/context/ApplicationContextLoader.java, stoservice/src/main/java/com/tutrit/stoservice/provider/DemoDataLoader.java, stoservice/src/main/java/com/tutrit/stoservice/provider/MessageProvider.java, stoservice/src/main/java/com/tutrit/stoservice/provider/SendMessageJob.java, stoservice/src/main/java/com/tutrit/stoservice/repository/UserMessageRepository.java, stoservice/src/main/java/com/tutrit/stoservice/service/MenuService.java
https://schneidervs.atlassian.net/browse/TGBOT-119
=> [Tgbot-119] Create send message job

README.md, stoservice/src/main/java/com/tutrit/stoservice/controller/Command.java, stoservice/src/main/java/com/tutrit/stoservice/controller/RequestDispatcher.java, stoservice/src/main/java/com/tutrit/stoservice/controller/UserController.java, stoservice/src/main/java/com/tutrit/stoservice/service/UserService.java, stoservice/src/main/java/com/tutrit/stoservice/utils/GetCommand.java
https://schneidervs.atlassian.net/jira/software/projects/TGBOT/boards/2?selectedIssue=TGBOT-123
=> [TGBOT-123]-Register user feature

stoservice/src/main/java/com/tutrit/stoservice/controller/Command.java, stoservice/src/main/java/com/tutrit/stoservice/controller/EngineerController.java, stoservice/src/main/java/com/tutrit/stoservice/controller/OrderController.java, stoservice/src/main/java/com/tutrit/stoservice/controller/RequestDispatcher.java, stoservice/src/main/java/com/tutrit/stoservice/service/EngineerService.java, stoservice/src/main/java/com/tutrit/stoservice/service/OrderService.java, stoservice/src/main/java/com/tutrit/stoservice/utils/GetMap.java, stoservice/src/main/java/com/tutrit/stoservice/utils/UserInputToEngineer.java, stoservice/src/main/java/com/tutrit/stoservice/utils/UserInputToOrder.java, stoservice/src/test/java/com/tutrit/stoservice/controller/EngineerControllerTest.java, stoservice/src/test/java/com/tutrit/stoservice/controller/OrderControllerTest.java, stoservice/src/test/java/com/tutrit/stoservice/repository/CustomerRepositoryTest.java, stoservice/src/test/java/com/tutrit/stoservice/service/EngineerServiceTest.java, stoservice/src/test/java/com/tutrit/stoservice/service/OrderServiceTest.java, stoservice/src/test/java/com/tutrit/stoservice/service/mock/EngineerRepositoryMock.java, stoservice/src/test/java/com/tutrit/stoservice/service/mock/OrderRepositoryMock.java, stoservice/src/test/java/com/tutrit/stoservice/utils/GetMapTest.java
https://schneidervs.atlassian.net/browse/TGBOT-77
=> TGBOT-77 process command get order {id}

stoservice/src/main/java/com/tutrit/stoservice/controller/CarController.java, stoservice/src/main/java/com/tutrit/stoservice/controller/Command.java, stoservice/src/main/java/com/tutrit/stoservice/controller/RequestDispatcher.java, stoservice/src/main/java/com/tutrit/stoservice/repository/CarRepository.java, stoservice/src/main/java/com/tutrit/stoservice/service/CarService.java
https://schneidervs.atlassian.net/browse/TGBOT-76
=> [Tgbot-76] process command get car

stoservice/src/main/java/com/tutrit/stoservice/mapper/MapToUser.java, stoservice/src/main/java/com/tutrit/stoservice/utils/UserInputToCustomer.java
=> Refactor_User_unput_by_casts_Map

stoservice/src/main/java/com/tutrit/stoservice/controller/RequestDispatcher.java, stoservice/src/main/java/com/tutrit/stoservice/controller/UserController.java
Fix bug for requestDispatcher
https://schneidervs.atlassian.net/browse/TGBOT-192
=> [TGBOT-192] Fix bug for requestDispatcher

stoservice/src/main/java/com/tutrit/stoservice/bean/Car.java, stoservice/src/main/java/com/tutrit/stoservice/controller/CarController.java, stoservice/src/main/java/com/tutrit/stoservice/provider/CarProvider.java, stoservice/src/main/java/com/tutrit/stoservice/repository/CarRepository.java, stoservice/src/main/java/com/tutrit/stoservice/util/ParseCar.java, stoservice/src/test/java/com/tutrit/stoservice/controller/CarControllerTest.java, stoservice/src/test/java/com/tutrit/stoservice/mock/CarRepositoryMock.java, stoservice/src/test/java/com/tutrit/stoservice/repository/CarRepositoryTest.java, stoservice/src/test/java/com/tutrit/stoservice/service/CarServiceTest.java
https://schneidervs.atlassian.net/browse/TGBOT-169
Added new fields and fixed tests
=> [Tgbot-169] Add vin plate number and owner to car bean

stoservice/src/main/java/com/tutrit/stoservice/bean/Order.java
https://schneidervs.atlassian.net/browse/TGBOT-171
=> [TGBOT-171] Add fields "Customer", List<Engeneer>, "User" and "Car" to class Order bean

stoservice/src/main/java/com/tutrit/stoservice/bean/Order.java, stoservice/src/main/java/com/tutrit/stoservice/provider/DemoDataLoader.java, stoservice/src/main/java/com/tutrit/stoservice/provider/OrderProvider.java
https://schneidervs.atlassian.net/browse/TGBOT-172
=> [TGBOT-172] DemoDataLoader instead of using date from provider create of 5 predefined orders

stoservice/src/main/java/com/tutrit/stoservice/context/ApplicationContextLoader.java, stoservice/src/main/java/com/tutrit/stoservice/settings/Configurations.java
https://schneidervs.atlassian.net/browse/TGBOT-163
=> [TGBOT-163] Load config .properties into application configuration

stoservice/src/main/java/com/tutrit/stoservice/StoserviceApplication.java, stoservice/src/main/java/com/tutrit/stoservice/settings/Configurations.java, stoservice/src/main/resources/config.properties
https://schneidervs.atlassian.net/browse/TGBOT-162
=> [TGBOT-162] Create configuration class

stoservice/src/main/java/com/tutrit/stoservice/repository/CustomerRepository.java, stoservice/src/test/java/com/tutrit/stoservice/repository/CustomerRepositoryTest.java
https://schneidervs.atlassian.net/browse/TGBOT-68
=> [Tgbot-68] Replace access level on customer repository for customers property

stoservice/src/main/java/com/tutrit/stoservice/repository/EngineerRepository.java, stoservice/src/main/java/com/tutrit/stoservice/util/EngineerRepositoryToOurFormat.java, stoservice/src/test/java/com/tutrit/stoservice/util/EngineerRepositoryToOurFormatTest.java, stoservice/src/test/java/com/tutrit/stoservice/util/GetBodyAsMapTest.java
https://schneidervs.atlassian.net/jira/software/projects/TGBOT/boards/2?selectedIssue=TGBOT-251
=> [Tgbot-251] Save the engineer repository to a specific file

stoservice/src/main/java/com/tutrit/stoservice/util/CarRepositoryToOurFormat.java, stoservice/src/test/java/com/tutrit/stoservice/util/CarRepositoryToOurFormatTest.java
https://schneidervs.atlassian.net/jira/software/projects/TGBOT/boards/2?selectedIssue=TGBOT-255
=> [TGBOT-255] created class and tests for save car repository in our format

stoservice/src/main/java/com/tutrit/stoservice/util/CarRepositoryToXml.java, stoservice/src/test/java/com/tutrit/stoservice/util/CarRepositoryToXmlTest.java
https://schneidervs.atlassian.net/jira/software/projects/TGBOT/boards/2?selectedIssue=TGBOT-252
=> [TGBOT-252] Created class and tests for save car repository to xml

stoservice/src/main/java/com/tutrit/stoservice/util/CustomerRepositoryToXml.java, stoservice/src/test/java/com/tutrit/stoservice/util/CustomerRepositoryToXmlTest.java
https://schneidervs.atlassian.net/jira/software/projects/TGBOT/boards/2?selectedIssue=TGBOT-253
=> [TGBOT-253] Created class for save customer repository to xml

stoservice/src/main/webapp/WEB-INF/header.html, stoservice/src/main/webapp/index.jsp
https://schneidervs.atlassian.net/jira/software/projects/TGBOT/boards/2?selectedIssue=TGBOT-213
https://schneidervs.atlassian.net/jira/software/projects/TGBOT/boards/2?selectedIssue=TGBOT-212
https://schneidervs.atlassian.net/jira/software/projects/TGBOT/boards/2?selectedIssue=TGBOT-214
In this request were closed three tasks
=> [TGBOT-213] Create index jsp page

stoservice/pom.xml, stoservice/src/main/java/com/tutrit/stoservice/context/ApplicationContext.java, stoservice/src/main/java/com/tutrit/stoservice/context/ApplicationContextLoader.java
Updated ApplicationContext and pom.xml
=> CONTEXT AND POM

stoservice/src/main/java/com/tutrit/stoservice/StoserviceApplication.java, stoservice/src/main/java/com/tutrit/stoservice/context/ApplicationContextLoader.java, stoservice/src/main/java/com/tutrit/stoservice/settings/ArgsSetup.java, stoservice/src/main/java/com/tutrit/stoservice/settings/Configurations.java, stoservice/src/test/java/com/tutrit/stoservice/settings/ArgsSetupTest.java
https://schneidervs.atlassian.net/browse/TGBOT-49
=> TGBOT-49 Add disable loading data flag

stoservice/src/main/webapp/WEB-INF/view/carCard.jsp, stoservice/src/main/webapp/WEB-INF/view/carDelete.jsp, stoservice/src/main/webapp/WEB-INF/view/header.html
https://schneidervs.atlassian.net/jira/software/projects/TGBOT/boards/2?selectedIssue=TGBOT-227
=> [TGBOT-227] Create delete car jsp page

stoservice/src/main/java/com/tutrit/stoservice/servlets/CarForm.java, stoservice/src/main/java/com/tutrit/stoservice/servlets/CarFormServlet.java, stoservice/src/main/webapp/WEB-INF/view/carForm.jsp, stoservice/src/main/webapp/WEB-INF/web.xml
https://schneidervs.atlassian.net/jira/software/projects/TGBOT/boards/2?selectedIssue=TGBOT-219
=> [TGBOT-219] Create car form jsp page

stoservice/src/main/webapp/WEB-INF/view/customerCard.jsp
https://schneidervs.atlassian.net/jira/software/projects/TGBOT/boards/2?selectedIssue=TGBOT-224
[TGBOT-224]: https://schneidervs.atlassian.net/browse/TGBOT-224?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [TGBOT-224] add customerCard.jsp

stoservice/src/main/java/com/tutrit/stoservice/servlets/CustomersTableServlet.java, stoservice/src/main/webapp/WEB-INF/view/customerTable.jsp, stoservice/src/main/webapp/WEB-INF/web.xml
https://schneidervs.atlassian.net/browse/TGBOT-216
=> [TGBOT-216] Make customer.jsp page

stoservice/src/main/java/com/tutrit/stoservice/context/ApplicationContextLoader.java, stoservice/src/main/java/com/tutrit/stoservice/service/InMemoryAuthenticationService.java, stoservice/src/test/java/com/tutrit/stoservice/service/InMemoryAuthenticationServiceTest.java
https://schneidervs.atlassian.net/jira/software/projects/TGBOT/boards/2?selectedIssue=TGBOT-267
[TGBOT-267]: https://schneidervs.atlassian.net/browse/TGBOT-267?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [TGBOT-267] Create in memory authentication service

stoservice/src/main/webapp/WEB-INF/view/orderDel.jsp
https://schneidervs.atlassian.net/jira/software/projects/TGBOT/boards/2?selectedIssue=TGBOT-229
=> TGBOT-229-Create-delete-order-jsp-page

stoservice/src/main/webapp/WEB-INF/view/orderCard.jsp
https://schneidervs.atlassian.net/jira/software/projects/TGBOT/boards/2?selectedIssue=TGBOT-225
[TGBOT-225]: https://schneidervs.atlassian.net/browse/TGBOT-225?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TGBOT-225 add orderCard.jsp

stoservice/src/main/java/com/tutrit/stoservice/servlets/OrderFormServlet.java, stoservice/src/main/webapp/WEB-INF/view/orderForm.jsp, stoservice/src/main/webapp/WEB-INF/web.xml
https://schneidervs.atlassian.net/jira/software/projects/TGBOT/boards/2?selectedIssue=TGBOT-221
[TGBOT-221]: https://schneidervs.atlassian.net/browse/TGBOT-221?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Tgbot 221 create order form jsp page

stoservice/src/main/java/com/tutrit/stoservice/servlets/OrderTableServlet.java, stoservice/src/main/webapp/WEB-INF/view/orderTable.jsp, stoservice/src/main/webapp/WEB-INF/web.xml
https://schneidervs.atlassian.net/browse/TGBOT-218
[TGBOT-218]: https://schneidervs.atlassian.net/browse/TGBOT-218?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [TGBOT-218] Make order jsp page

stoservice/src/main/java/com/tutrit/stoservice/servlets/EngineerTableServlet.java, stoservice/src/main/webapp/WEB-INF/view/engineersTable.jsp
https://schneidervs.atlassian.net/browse/TGBOT-217
=> [TGBOT-217] Make engineer jsp-page

stoservice/src/main/java/com/tutrit/stoservice/repository/EngineerRepository.java, stoservice/src/main/java/com/tutrit/stoservice/servlets/EngineerCardServlet.java, stoservice/src/main/webapp/WEB-INF/view/engineerCard.jsp
https://schneidervs.atlassian.net/browse/TGBOT-226
=> [TGBOT-226] Add card for Engineer jsp-page

stoservice/src/main/java/com/tutrit/stoservice/servlets/EngineerFormServlet.java, stoservice/src/main/webapp/WEB-INF/view/engineerForm.jsp
https://schneidervs.atlassian.net/browse/TGBOT-222
=> [TGBOT-222] Create Engineer form jsp-page

stoservice/src/test/java/com/tutrit/stoservice/controller/CustomerControllerTest.java, stoservice/src/test/java/com/tutrit/stoservice/controller/EngineerControllerTest.java, stoservice/src/test/java/com/tutrit/stoservice/controller/OrderControllerTest.java, stoservice/src/test/java/com/tutrit/stoservice/mock/OrderrRepositoryUUIDMock.java
https://schneidervs.atlassian.net/browse/TGBOT-208
=> [TGBOT-208] Change test for engineer controller and oder controller

.github/workflows/gradle.yml
https://schneidervs.atlassian.net/browse/TGBOT-202
=> [TGBOT-202] Create git action to build project on every push

stoservice/build.gradle, stoservice/pom.xml
https://schneidervs.atlassian.net/browse/TGBOT-203
=> [TGBOT-203]-add-jacoco-framework

pom.xml
https://schneidervs.atlassian.net/browse/TGBOT-276
=> [TGBOT-276] Create parent pom.xml
